### ISSUE TITLE
Incorrect indent in this line.

### ISSUE THREAD

**Issue by vskubriev** [Anshelen/microservices-deploy#1]
https://github.com/Anshelen/microservices-deploy/blob/6277c229bc58fc75f25108c1c3673a6e3aab5901/jenkins/Jenkinsfile-backend#L22

**Comment by Anshelen** [comment]
Hi. It seems that it is correct. That stages block is nested in stage "Prepare container"

**Comment by vskubriev** [comment]
It seems you are right. See screen in vscode. 
![image](https://user-images.githubusercontent.com/4639077/194546527-22ddb918-01f2-4a69-a7de-4d1527d74c4c.png)

Sorry.

**Comment by vskubriev** [comment]
Stages could be inside parent stage block in Jenkinsfile ?

**Comment by Anshelen** [comment]
Yep, that is supported. It helps if we need to declare something common for a few stages (here we use the same docker agent for the first three stages)
